name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install -r requirements.txt
        python -m pip install twine wheel
    - name: Running Tests
      run: |
        python test.py
    - name: Publish
      run: |
        make dep
        python -m twine upload dist/* -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    name: ${{ matrix.os }} Python ${{ matrix.python }}
